/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfase;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import operaciones.Operaciones;
import operaciones.clsOrdenDeServicio;

/**
 *
 * @author Usuario
 */
public class jPanelOSabierta extends javax.swing.JPanel {
    private DefaultTableModel model;
    private Principal principal;
    private jPanelCerrarOrden cerrarOrden;
    private String[] cosa;
    int filaDeLaTabla = 0;
    private ArrayList borrados = new ArrayList();
    String[] DatosDeBorrados = new String[4];
    /**
     * Creates new form jPanelOSabierta
     */
    public jPanelOSabierta() {
        initComponents();
        iniciarDatos();
    }

    jPanelOSabierta(Principal aThis) {
       this.principal = aThis;
       initComponents();
       iniciarDatos();
    }
    
    public void rellenarTabla(String[] correccion){
        this.cosa = correccion;
        this.model.addRow(correccion);
        this.jTableOS.setModel(model);
        
    }
    public void iniciarDatos(){
        int i=0;
        this.jButtonCerrarOrden.setEnabled(false);
        Operaciones operac = new Operaciones();
        ArrayList uni = new ArrayList();
           
           uni = operac.listarOSabierta();
           
            String[] titulos = {"Numero de Orden", "Unidad", "Fecha", "Generada Por"}; 
              model = new DefaultTableModel(null, titulos){
                  @Override
                  public boolean isCellEditable(int row, int column) {
                   //all cells false
                  return false;
                  }
              };
              String[] fila = new String[4];
              clsOrdenDeServicio claseOrden = new clsOrdenDeServicio();
              for (i=0; i<uni.size(); i++){
              claseOrden = (clsOrdenDeServicio) uni.get(i);
              
              fila[0] = Integer.toString(claseOrden.getNumeroOrden());
              fila[1] = claseOrden.getMatricula();
              fila[2] = claseOrden.getFecha();
              fila[3] = claseOrden.getGenera();                         
              model.addRow(fila);
              }
             this.jTableOS.setModel(model);
                
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOS = new javax.swing.JTable();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonCerrarOrden = new javax.swing.JButton();

        setPreferredSize(getMaximumSize());

        jTableOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero de Orden", "Unidad", "Fecha", "Generada Por"
            }
        ));
        jTableOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableOSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableOS);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setEnabled(false);
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonCerrarOrden.setText("Cerrar Orden");
        jButtonCerrarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarOrdenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCerrarOrden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCerrarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableOSMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()){
                this.jButtonCerrarOrden.setEnabled(true);
                
                this.filaDeLaTabla = jTableOS.getSelectedRow();
                DatosDeBorrados[0] = (String) model.getValueAt(filaDeLaTabla, 0);
                DatosDeBorrados[1] = (String) model.getValueAt(filaDeLaTabla, 1);
                DatosDeBorrados[2] = (String) model.getValueAt(filaDeLaTabla, 2);
                DatosDeBorrados[3] = (String) model.getValueAt(filaDeLaTabla, 3);
                
                this.borrados.add(DatosDeBorrados);
                //model.removeRow(filaDeLaTabla);
                this.jTableOS.setModel(model);
                
        }
    }//GEN-LAST:event_jTableOSMouseClicked

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        //if (justificacion.isEmpty()){
            JOptionPane.showMessageDialog(null,"Hola aun sin determinar");
       // }

    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.setVisible(false);
        this.jButtonCerrarOrden.setEnabled(false);
        super.remove(this);
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonCerrarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarOrdenActionPerformed
        // = new jPanelCerrarOrden();
             if (cerrarOrden==null){ 
                this.cerrarOrden = new jPanelCerrarOrden(Integer.parseInt(DatosDeBorrados[0]), model, filaDeLaTabla);
                principal.add(cerrarOrden, 0);
                principal.pack();
                cerrarOrden.setVisible(true);
                this.setVisible(false);
            }else{
                 cerrarOrden.setVisible(true);
            }
            
    }//GEN-LAST:event_jButtonCerrarOrdenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCerrarOrden;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableOS;
    // End of variables declaration//GEN-END:variables
}
